### ISSUE TITLE
Whole tracking is too big for the maximum buffer size

### ISSUE THREAD

**Issue by carlOSx64** [nilgoyette/diffusion-slice-rs#14]
I noticed this fatal error after submitting my last PR. I tried to render `Whole_Brain_Tracking/Subject__whole_brain_wm_tracts_det_comp.trk`. This can be fixed; it just means that we can't batch the whole brain in a single buffer. We'll have to work on a system that supports multiple batches.
```
[2024-08-05T00:51:40Z ERROR wgpu::backend::wgpu_core] Handling wgpu errors as fatal by default
thread 'main' panicked at /home/carl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
      note: label = `FiberVertexBuffer`
    Buffer size 866706696 is greater than the maximum buffer size (268435456)
```

**Comment by carlOSx64** [comment]
There is one positive side effect to this constraint. Since we need to allocate multiple buffers on the GPU, we don't need to keep the whole streamlines data all at once in the program memory when creating the buffers.

**Comment by carlOSx64** [comment]
I worked on the fix, we can now render the whole brain tracking
![image](https://github.com/user-attachments/assets/23bdb888-d77f-4184-b796-bed170a35e15)
The first execution took more time (around 2.5s), the 9 default images are generated. I don't expect the time to raise that much from this point.
`[2024-08-07T01:42:53Z INFO  diffusion_slice_rs] Program duration: 1.596090084s`
This is close to what MI-Brain displays (I think?)
![image](https://github.com/user-attachments/assets/af888d53-6b7f-4623-8231-44fbfb290a8a)
I will push this in a future PR.

**Comment by nilgoyette** [comment]
Loading and displaying a full brain is somewhat slow in MI-Brain. That's why there are some options to avoid displaying everything (it's kinda useless anyway).
